/**
 * island_data.c — Mutable island definitions and procedural tree generation.
 *
 * Kept in a .c file (not the header) so that islands_generate_trees() can
 * populate wood-resource positions at server startup without fighting const.
 *
 * Tree coverage: every polygon island whose grass_poly_scale > 0 gets a
 * regular grid of trees (spacing TREE_GRID_SPACING px) with per-tree random
 * jitter.  Only grid points that fall inside the scaled grass polygon are
 * accepted.  Non-wood resources (fiber, rock) are defined statically below
 * and are NOT overwritten by this function.
 */

#include "sim/island.h"
#include <string.h>
#include <math.h>
#include <stdbool.h>

/* ── Island data ─────────────────────────────────────────────────────────── */

IslandDef ISLAND_PRESETS[ISLAND_COUNT] = {
    /* ── Island 1: Tropical bump-circle island ─────────────────────────── */
    {
        .id              = 1,
        .x               = 800.0f,
        .y               = 600.0f,
        .beach_radius_px = 185.0f,
        .grass_radius_px = 148.0f,
        /* Mirror of client RenderSystem.ISLAND_PRESETS['tropical'].beachBumps */
        .beach_bumps     = { 0, 14, -9, 20,  6, -13, 16,  3, -7, 18, -5, 10, 12, -11,  7, -9 },
        .beach_max_bump  = 20.0f,
        /* Mirror of client RenderSystem.ISLAND_PRESETS['tropical'].grassBumps */
        .grass_bumps     = { 0,  9, -6, 13,  4,  -9, 10,  2, -4, 11, -3,  7,  8,  -7,  5, -6 },
        .grass_max_bump  = 13.0f,
        .preset          = "tropical",
        .resource_count  = 10,
        .resources = {
            { .ox = -65.0f, .oy = -55.0f, .type = ISLAND_RES_WOOD  },
            { .ox =  85.0f, .oy = -25.0f, .type = ISLAND_RES_WOOD  },
            { .ox =  15.0f, .oy =  80.0f, .type = ISLAND_RES_WOOD  },
            { .ox = -90.0f, .oy =  38.0f, .type = ISLAND_RES_WOOD  },
            { .ox =  45.0f, .oy = -78.0f, .type = ISLAND_RES_FIBER },
            { .ox = -28.0f, .oy =  32.0f, .type = ISLAND_RES_FIBER },
            { .ox =  70.0f, .oy =  50.0f, .type = ISLAND_RES_FIBER },
            { .ox =  -5.0f, .oy = -90.0f, .type = ISLAND_RES_ROCK  },
            { .ox =  60.0f, .oy =  75.0f, .type = ISLAND_RES_ROCK  },
            { .ox = -75.0f, .oy = -15.0f, .type = ISLAND_RES_ROCK  },
        },
    },

    /* ── Island 2: Giant continental landmass ──────────────────────────── *
     * ~6200 × 6100 px, centre (6000, 5000).                                *
     * Wood resources are left empty here — islands_generate_trees() fills  *
     * them procedurally at startup.                                         */
    {
        .id               = 2,
        .x                = 6000.0f,
        .y                = 5000.0f,
        .beach_radius_px  = 0.0f,
        .grass_radius_px  = 0.0f,
        .beach_bumps      = {0},
        .grass_bumps      = {0},
        .beach_max_bump   = 0.0f,
        .grass_max_bump   = 0.0f,
        .preset           = "continental",
        .vertex_count     = 28,
        .poly_bound_r     = 3300.0f,
        .grass_poly_scale = 0.82f,
        /*             N     NNE    NE    ENE   E-NE  E-near   E    ESE */
        .vx = {        0,   800, 1600, 2300, 2750,  2950, 3100, 2900,
        /*            SE    SSE   S-SE     S  S-bay bay-in bay-fl bay-in */
                    2550,  1950,  1250,   500,  250,   100,    0,  -100,
        /*         bay-ex  SW-S    SW    WSW  W-SW  W-near    W    WNW  */
                    -350, -1050, -1850, -2450, -2850, -2950, -3100, -2900,
        /*            NW    NNW   N-NW  N-near */
                   -2550, -1950, -1250,  -500 },
        /*             N     NNE    NE    ENE   E-NE  E-near   E    ESE */
        .vy = {    -3000, -2850, -2650, -2250, -1450,  -500,  400, 1200,
        /*            SE    SSE   S-SE     S  S-bay bay-in bay-fl bay-in */
                    2050,  2600,  2900,  3050,  2450,  1850, 1650, 1850,
        /*         bay-ex  SW-S    SW    WSW  W-SW  W-near    W    WNW  */
                    2450,  2950,  2650,  2150,  1450,   500, -400, -1250,
        /*            NW    NNW   N-NW  N-near */
                   -2050, -2550, -2800, -2950 },

        /* Static non-wood resources — wood is generated by islands_generate_trees() */
        .resource_count = 8,
        .resources = {
            /* Fiber — meadow patches */
            { .ox =  -800.0f, .oy = -1000.0f, .type = ISLAND_RES_FIBER },
            { .ox =  1000.0f, .oy = -1000.0f, .type = ISLAND_RES_FIBER },
            { .ox =  1200.0f, .oy =  1000.0f, .type = ISLAND_RES_FIBER },
            { .ox = -1500.0f, .oy =  -400.0f, .type = ISLAND_RES_FIBER },
            /* Rock — mountain outcrops near the edges */
            { .ox = -2500.0f, .oy = -1600.0f, .type = ISLAND_RES_ROCK  },
            { .ox =  2500.0f, .oy = -1000.0f, .type = ISLAND_RES_ROCK  },
            { .ox =  2400.0f, .oy =  1600.0f, .type = ISLAND_RES_ROCK  },
            { .ox = -2500.0f, .oy =  1400.0f, .type = ISLAND_RES_ROCK  },
        },
    },
};

/* ── Tree generation ─────────────────────────────────────────────────────── */

/* Grid spacing between trees (client pixels). */
#define TREE_GRID_SPACING 160.0f
/* Half-amplitude of per-tree random jitter (client pixels). */
#define TREE_JITTER       40.0f

/**
 * Returns non-zero if world point (px, py) lies inside the scaled grass
 * polygon of the island (ray-cast even–odd rule).
 */
static int inside_grass_poly(const IslandDef *isl, float px, float py)
{
    int   n      = isl->vertex_count;
    float scale  = isl->grass_poly_scale;
    int   inside = 0;

    for (int i = 0, j = n - 1; i < n; j = i++) {
        /* Grass polygon vertex = island centre + offset × scale */
        float xi = isl->x + isl->vx[i] * scale;
        float yi = isl->y + isl->vy[i] * scale;
        float xj = isl->x + isl->vx[j] * scale;
        float yj = isl->y + isl->vy[j] * scale;

        if ((yi > py) != (yj > py) &&
            px < (xj - xi) * (py - yi) / (yj - yi) + xi)
            inside = !inside;
    }
    return inside;
}

/* ── Resource size hash ─────────────────────────────────────────────────────
 * Derives a deterministic size scale [0.5, 1.8] from a resource's ox/oy.
 * Matches the JavaScript hash used by the client for visual consistency.
 */
static float resource_size_from_offset(float ox, float oy)
{
    unsigned int h  = ((unsigned int)(int)ox * 2654435761u) ^ ((unsigned int)(int)oy * 1664525u);
    unsigned int h2 = (h * 2246822519u) ^ ((h >> 13) * 2654435761u);
    (void)h2;
    return 0.5f + ((float)(h & 0xFFu) / 255.0f) * 1.3f;
}

static int resource_max_health(const char *type)
{
    if (strcmp(type, ISLAND_RES_WOOD)  == 0) return 100;
    if (strcmp(type, ISLAND_RES_ROCK)  == 0) return  60;
    if (strcmp(type, ISLAND_RES_FIBER) == 0) return  30;
    return 50;
}

/* Apply size + health to every pre-defined resource in ISLAND_PRESETS[]. */
static void init_static_resource_fields(void)
{
    for (int ii = 0; ii < ISLAND_COUNT; ii++) {
        IslandDef *isl = &ISLAND_PRESETS[ii];
        for (int ri = 0; ri < isl->resource_count; ri++) {
            IslandResource *r = &isl->resources[ri];
            r->size       = resource_size_from_offset(r->ox, r->oy);
            r->max_health = resource_max_health(r->type);
            r->health     = r->max_health;
        }
    }
}


    /* First pass: stamp size+health onto all statically declared resources. */
    init_static_resource_fields();

    for (int ii = 0; ii < ISLAND_COUNT; ii++) {
        IslandDef *isl = &ISLAND_PRESETS[ii];

        /* Only polygon islands with a grass scale get procedural trees. */
        if (isl->vertex_count == 0 || isl->grass_poly_scale <= 0.0f) continue;

        float half_bound = isl->poly_bound_r * isl->grass_poly_scale;

        /* Deterministic LCG seeded per island — no stdlib rand dependency. */
        unsigned int seed = (unsigned int)((unsigned int)isl->id * 1664525u + 1013904223u);

        float x0 = isl->x - half_bound;
        float x1 = isl->x + half_bound;
        float y0 = isl->y - half_bound;
        float y1 = isl->y + half_bound;

        int added = 0;
        for (float gx = x0; gx <= x1 && isl->resource_count < ISLAND_MAX_RESOURCES; gx += TREE_GRID_SPACING) {
            for (float gy = y0; gy <= y1 && isl->resource_count < ISLAND_MAX_RESOURCES; gy += TREE_GRID_SPACING) {
                /* Two LCG steps for X and Y jitter in [-TREE_JITTER, +TREE_JITTER] */
                seed = seed * 1664525u + 1013904223u;
                float jx = ((float)(seed & 0xFFFFu) / 65535.0f - 0.5f) * (2.0f * TREE_JITTER);
                seed = seed * 1664525u + 1013904223u;
                float jy = ((float)(seed & 0xFFFFu) / 65535.0f - 0.5f) * (2.0f * TREE_JITTER);

                float tx = gx + jx;
                float ty = gy + jy;

                if (!inside_grass_poly(isl, tx, ty)) continue;

                IslandResource *r = &isl->resources[isl->resource_count];
                r->ox         = tx - isl->x;
                r->oy         = ty - isl->y;
                r->type       = ISLAND_RES_WOOD;
                r->size       = resource_size_from_offset(r->ox, r->oy);
                r->max_health = resource_max_health(ISLAND_RES_WOOD);
                r->health     = r->max_health;
                isl->resource_count++;
                added++;
            }
        }

        /* Log how many trees were generated for this island. */
        (void)added; /* suppress unused-variable warning if logging is off */
    }
}
