/**
 * island_data.c — Mutable island definitions and procedural tree generation.
 *
 * Kept in a .c file (not the header) so that islands_generate_trees() can
 * populate wood-resource positions at server startup without fighting const.
 *
 * Tree coverage: every polygon island whose grass_poly_scale > 0 gets a
 * regular grid of trees (spacing TREE_GRID_SPACING px) with per-tree random
 * jitter.  Only grid points that fall inside the scaled grass polygon are
 * accepted.  Non-wood resources (fiber, rock) are defined statically below
 * and are NOT overwritten by this function.
 */

#include "sim/island.h"
#include "net/websocket_server.h"  /* PlacedStructure — needed for island_resource_can_respawn */
#include <string.h>
#include <math.h>
#include <stdbool.h>

/* ── Island data ─────────────────────────────────────────────────────────── */

IslandDef ISLAND_PRESETS[ISLAND_COUNT] = {
    /* ── Island 1: Tropical bump-circle island ─────────────────────────── */
    {
        .id              = 1,
        .x               = 800.0f,
        .y               = 600.0f,
        .beach_radius_px = 185.0f,
        .grass_radius_px = 148.0f,
        /* Mirror of client RenderSystem.ISLAND_PRESETS['tropical'].beachBumps */
        .beach_bumps     = { 0, 14, -9, 20,  6, -13, 16,  3, -7, 18, -5, 10, 12, -11,  7, -9 },
        .beach_max_bump  = 20.0f,
        /* Mirror of client RenderSystem.ISLAND_PRESETS['tropical'].grassBumps */
        .grass_bumps     = { 0,  9, -6, 13,  4,  -9, 10,  2, -4, 11, -3,  7,  8,  -7,  5, -6 },
        .grass_max_bump  = 13.0f,
        .preset          = "tropical",
        .resource_count  = 10,
        .resources = {
            { .ox = -65.0f, .oy = -55.0f, .type_id = RES_WOOD  },
            { .ox =  85.0f, .oy = -25.0f, .type_id = RES_WOOD  },
            { .ox =  15.0f, .oy =  80.0f, .type_id = RES_WOOD  },
            { .ox = -90.0f, .oy =  38.0f, .type_id = RES_WOOD  },
            { .ox =  45.0f, .oy = -78.0f, .type_id = RES_FIBER },
            { .ox = -28.0f, .oy =  32.0f, .type_id = RES_FIBER },
            { .ox =  70.0f, .oy =  50.0f, .type_id = RES_FIBER },
            { .ox =  -5.0f, .oy = -90.0f, .type_id = RES_ROCK  },
            { .ox =  60.0f, .oy =  75.0f, .type_id = RES_ROCK  },
            { .ox = -75.0f, .oy = -15.0f, .type_id = RES_ROCK  },
        },
    },

    /* ── Island 2: Giant continental landmass ──────────────────────────── *
     * ~6200 × 6100 px, centre (6000, 5000).                                *
     * Wood resources are left empty here — islands_generate_trees() fills  *
     * them procedurally at startup.                                         */
    {
        .id               = 2,
        .x                = 6000.0f,
        .y                = 5000.0f,
        .beach_radius_px  = 0.0f,
        .grass_radius_px  = 0.0f,
        .beach_bumps      = {0},
        .grass_bumps      = {0},
        .beach_max_bump   = 0.0f,
        .grass_max_bump   = 0.0f,
        .preset           = "continental",
        .vertex_count     = 28,
        .poly_bound_r     = 3300.0f,
        .grass_poly_scale = 0.82f,
        /*             N     NNE    NE    ENE   E-NE  E-near   E    ESE */
        .vx = {        0,   800, 1600, 2300, 2750,  2950, 3100, 2900,
        /*            SE    SSE   S-SE     S  S-bay bay-in bay-fl bay-in */
                    2550,  1950,  1250,   500,  250,   100,    0,  -100,
        /*         bay-ex  SW-S    SW    WSW  W-SW  W-near    W    WNW  */
                    -350, -1050, -1850, -2450, -2850, -2950, -3100, -2900,
        /*            NW    NNW   N-NW  N-near */
                   -2550, -1950, -1250,  -500 },
        /*             N     NNE    NE    ENE   E-NE  E-near   E    ESE */
        .vy = {    -3000, -2850, -2650, -2250, -1450,  -500,  400, 1200,
        /*            SE    SSE   S-SE     S  S-bay bay-in bay-fl bay-in */
                    2050,  2600,  2900,  3050,  2450,  1850, 1650, 1850,
        /*         bay-ex  SW-S    SW    WSW  W-SW  W-near    W    WNW  */
                    2450,  2950,  2650,  2150,  1450,   500, -400, -1250,
        /*            NW    NNW   N-NW  N-near */
                   -2050, -2550, -2800, -2950 },

        /* Static non-wood resources — wood is generated by islands_generate_trees() */
        .resource_count = 8,
        .resources = {
            /* Fiber — meadow patches */
            { .ox =  -800.0f, .oy = -1000.0f, .type_id = RES_FIBER },
            { .ox =  1000.0f, .oy = -1000.0f, .type_id = RES_FIBER },
            { .ox =  1200.0f, .oy =  1000.0f, .type_id = RES_FIBER },
            { .ox = -1500.0f, .oy =  -400.0f, .type_id = RES_FIBER },
            /* Rock — mountain outcrops near the edges */
            { .ox = -2500.0f, .oy = -1600.0f, .type_id = RES_ROCK  },
            { .ox =  2500.0f, .oy = -1000.0f, .type_id = RES_ROCK  },
            { .ox =  2400.0f, .oy =  1600.0f, .type_id = RES_ROCK  },
            { .ox = -2500.0f, .oy =  1400.0f, .type_id = RES_ROCK  },
        },
    },

    /* ── Island 3: Crescent (horseshoe) — Combat Cove / Smuggler Cove ──────
     * ~10,000 × ~8,200 px, centre (-2500, 2500).  Opens southward.
     * Combat Cove = large inner bay between the two arms.
     * Smuggler Cove = secondary inlet on inner-west face of left arm.
     * Beach = concave cove on outer-east face of right arm.
     * CW winding in screen-space (y-down).                                  */
    {
        .id               = 3,
        .x                = -2500.0f,
        .y                =  2500.0f,
        .beach_radius_px  = 0.0f,
        .grass_radius_px  = 0.0f,
        .beach_bumps      = {0},
        .grass_bumps      = {0},
        .beach_max_bump   = 0.0f,
        .grass_max_bump   = 0.0f,
        .preset           = "continental",
        .vertex_count     = 70,
        .poly_bound_r     = 5800.0f,
        .grass_poly_scale = 0.82f,
        .vx = {
            -3152, -1494,  -296,  1457,  2926,  4400,  4900,  5000,
             4700,  4100,  3100,  3203,  3100,  2932,  2521,  1743,
             1061,   550,   248,   865,  1400,  1682,  1756,  2161,
             2695,  2879,  2916,  2566,  2179,  1719,  1498,  1166,
              835,   319,  -252,  -879, -1321, -1560, -1855, -2279,
            -2610, -2518, -2703, -3108, -3495, -3955, -4250, -4176,
            -3661, -3163, -2629, -2239, -2058, -1560,  -961, -1050,
            -1443, -1991, -2673, -3509, -4133, -4549, -4734, -4865,
            -5215, -5049, -4914, -5088, -4867, -4203,
        },
        .vy = {
            -3490, -3877, -4116, -3811, -2798, -1600,  -200,   700,
             1300,  1800,  2200,  2531,  2800,  3250,  3514,  3721,
             3826,  3866,  3289,  2594,  2200,  1649,  1041,  1612,
             1686,  1170,   875,   507,   378,   323,  -285,  -599,
            -1041, -1464, -1501, -1409,  -783,  -120,   396,   525,
              267,  -120,  -267,  -304,    -9,    83,   488,  1004,
             1152,  1152,  1115,  1561,  2268,  2859,  3321,  3787,
             3944,  3640,  3382,  3381,  3358,  3058,  2665,  2111,
             1392,   342,  -652, -1373, -2552, -3160,
        },
        .resource_count = 10,
        .resources = {
            { .ox = -3800.0f, .oy = -2000.0f, .type_id = RES_ROCK  },
            { .ox =  3500.0f, .oy = -1200.0f, .type_id = RES_ROCK  },
            { .ox = -2500.0f, .oy =  2800.0f, .type_id = RES_ROCK  },
            { .ox =  2200.0f, .oy =  2800.0f, .type_id = RES_ROCK  },
            { .ox = -3000.0f, .oy =  -800.0f, .type_id = RES_FIBER },
            { .ox =  2000.0f, .oy =  -600.0f, .type_id = RES_FIBER },
            { .ox = -1000.0f, .oy = -2000.0f, .type_id = RES_FIBER },
            { .ox =  -200.0f, .oy = -2500.0f, .type_id = RES_FIBER },
            { .ox = -3200.0f, .oy =  1600.0f, .type_id = RES_FIBER },
            { .ox =  2800.0f, .oy =  1500.0f, .type_id = RES_FIBER },
        },
    },
};

/* ── Tree generation ─────────────────────────────────────────────────────── */

/* Grid spacing between fiber plants (client pixels). */
#define TREE_GRID_SPACING 160.0f
/* Half-amplitude of per-tree random jitter (client pixels). */
#define TREE_JITTER       40.0f

/* Fiber-plant procedural density settings. */
#define FIBER_GRID_SPACING 280.0f
#define FIBER_JITTER        80.0f
/* Fiber is scattered over a slightly smaller polygon fraction to keep it
   interior and away from the rocky/treed edges. */
#define FIBER_POLY_SCALE    0.70f

/**
 * Returns non-zero if world point (px, py) lies inside the scaled grass
 * polygon of the island (ray-cast even–odd rule).
 */
static int inside_grass_poly(const IslandDef *isl, float px, float py)
{
    int   n      = isl->vertex_count;
    float scale  = isl->grass_poly_scale;
    int   inside = 0;

    for (int i = 0, j = n - 1; i < n; j = i++) {
        /* Grass polygon vertex = island centre + offset × scale */
        float xi = isl->x + isl->vx[i] * scale;
        float yi = isl->y + isl->vy[i] * scale;
        float xj = isl->x + isl->vx[j] * scale;
        float yj = isl->y + isl->vy[j] * scale;

        if ((yi > py) != (yj > py) &&
            px < (xj - xi) * (py - yi) / (yj - yi) + xi)
            inside = !inside;
    }
    return inside;
}

/* Variant of inside_grass_poly that uses an explicit polygon scale factor
   instead of the island's grass_poly_scale.  Used for fiber placement. */
static int inside_grass_poly_scaled(const IslandDef *isl, float px, float py, float scale)
{
    int n      = isl->vertex_count;
    int inside = 0;

    for (int i = 0, j = n - 1; i < n; j = i++) {
        float xi = isl->x + isl->vx[i] * scale;
        float yi = isl->y + isl->vy[i] * scale;
        float xj = isl->x + isl->vx[j] * scale;
        float yj = isl->y + isl->vy[j] * scale;

        if ((yi > py) != (yj > py) &&
            px < (xj - xi) * (py - yi) / (yj - yi) + xi)
            inside = !inside;
    }
    return inside;
}

/* ── Resource size hash ─────────────────────────────────────────────────────
 * Derives a deterministic size scale [0.5, 1.8] from a resource's ox/oy.
 * Matches the JavaScript hash used by the client for visual consistency.
 */
static float resource_size_from_offset(float ox, float oy)
{
    unsigned int h  = ((unsigned int)(int)ox * 2654435761u) ^ ((unsigned int)(int)oy * 1664525u);
    unsigned int h2 = (h * 2246822519u) ^ ((h >> 13) * 2654435761u);
    (void)h2;
    return 0.5f + ((float)(h & 0xFFu) / 255.0f) * 1.3f;
}

static int resource_max_health(uint8_t type_id)
{
    switch (type_id) {
        case RES_WOOD:  return 100;
        case RES_ROCK:  return  60;
        case RES_FIBER: return  30;
        default:        return  50;
    }
}

/* Apply size + health to every pre-defined resource in ISLAND_PRESETS[]. */
static void init_static_resource_fields(void)
{
    for (int ii = 0; ii < ISLAND_COUNT; ii++) {
        IslandDef *isl = &ISLAND_PRESETS[ii];
        for (int ri = 0; ri < isl->resource_count; ri++) {
            IslandResource *r = &isl->resources[ri];
            r->size       = resource_size_from_offset(r->ox, r->oy);
            r->max_health = resource_max_health(r->type_id);
            r->health     = r->max_health;
        }
    }
}

void islands_generate_trees(void)
{
    /* First pass: stamp size+health onto all statically declared resources. */
    init_static_resource_fields();

    for (int ii = 0; ii < ISLAND_COUNT; ii++) {
        IslandDef *isl = &ISLAND_PRESETS[ii];

        /* Only polygon islands with a grass scale get procedural trees. */
        if (isl->vertex_count == 0 || isl->grass_poly_scale <= 0.0f) continue;

        float half_bound = isl->poly_bound_r * isl->grass_poly_scale;

        /* One deterministic seed per island — the fiber pass derives its own
         * stream from the same formula XOR'd with a golden-ratio constant. */
        unsigned int seed = (unsigned int)((unsigned int)isl->id * 1664525u + 1013904223u);

        float x0 = isl->x - half_bound;
        float x1 = isl->x + half_bound;
        float y0 = isl->y - half_bound;
        float y1 = isl->y + half_bound;

        int added = 0;
        for (float gx = x0; gx <= x1 && isl->resource_count < ISLAND_MAX_RESOURCES; gx += TREE_GRID_SPACING) {
            for (float gy = y0; gy <= y1 && isl->resource_count < ISLAND_MAX_RESOURCES; gy += TREE_GRID_SPACING) {
                /* Two LCG steps for X and Y jitter in [-TREE_JITTER, +TREE_JITTER] */
                seed = seed * 1664525u + 1013904223u;
                float jx = ((float)(seed & 0xFFFFu) / 65535.0f - 0.5f) * (2.0f * TREE_JITTER);
                seed = seed * 1664525u + 1013904223u;
                float jy = ((float)(seed & 0xFFFFu) / 65535.0f - 0.5f) * (2.0f * TREE_JITTER);

                float tx = gx + jx;
                float ty = gy + jy;

                if (!inside_grass_poly(isl, tx, ty)) continue;

                IslandResource *r = &isl->resources[isl->resource_count];
                r->ox         = tx - isl->x;
                r->oy         = ty - isl->y;
                r->type_id    = RES_WOOD;
                r->size       = resource_size_from_offset(r->ox, r->oy);
                r->max_health = resource_max_health(RES_WOOD);
                r->health     = r->max_health;
                isl->resource_count++;
                added++;
            }
        }

        /* Log how many trees were generated for this island. */
        (void)added; /* suppress unused-variable warning if logging is off */
    }

    /* ── Second pass: procedural fiber (tall-grass) for polygon islands ── */
    for (int ii = 0; ii < ISLAND_COUNT; ii++) {
        IslandDef *isl = &ISLAND_PRESETS[ii];

        if (isl->vertex_count == 0 || isl->grass_poly_scale <= 0.0f) continue;

        /* Derive fiber seed from the same island seed formula as the tree pass,
         * XOR'd with a golden-ratio constant to give an independent jitter stream
         * from the same world identity — no separate magic seed constant needed. */
        unsigned int island_seed = (unsigned int)((unsigned int)isl->id * 1664525u + 1013904223u);
        unsigned int seed = island_seed ^ 0x9E3779B9u;

        /* Use a reduced polygon scale so fiber stays well inside the island. */
        float fiber_scale = isl->grass_poly_scale * FIBER_POLY_SCALE;
        float half_bound  = isl->poly_bound_r * fiber_scale;

        /* Shift fiber grid origin by half a cell in both axes — this is the
         * primary guarantee that fiber can never land on a tree grid point
         * even if the jitter RNG produced identical values. */
        float x0 = isl->x - half_bound + FIBER_GRID_SPACING * 0.5f;
        float x1 = isl->x + half_bound;
        float y0 = isl->y - half_bound + FIBER_GRID_SPACING * 0.5f;
        float y1 = isl->y + half_bound;

        int added_fiber = 0;
        for (float gx = x0; gx <= x1 && isl->resource_count < ISLAND_MAX_RESOURCES; gx += FIBER_GRID_SPACING) {
            for (float gy = y0; gy <= y1 && isl->resource_count < ISLAND_MAX_RESOURCES; gy += FIBER_GRID_SPACING) {
                seed = seed * 1664525u + 1013904223u;
                float jx = ((float)(seed & 0xFFFFu) / 65535.0f - 0.5f) * (2.0f * FIBER_JITTER);
                seed = seed * 1664525u + 1013904223u;
                float jy = ((float)(seed & 0xFFFFu) / 65535.0f - 0.5f) * (2.0f * FIBER_JITTER);

                float fx = gx + jx;
                float fy = gy + jy;

                /* Must be inside the reduced grass polygon. */
                if (!inside_grass_poly_scaled(isl, fx, fy, fiber_scale)) continue;

                IslandResource *r = &isl->resources[isl->resource_count];
                r->ox         = fx - isl->x;
                r->oy         = fy - isl->y;
                r->type_id    = RES_FIBER;
                r->size       = resource_size_from_offset(r->ox, r->oy);
                r->max_health = resource_max_health(RES_FIBER);
                r->health     = r->max_health;
                isl->resource_count++;
                added_fiber++;
            }
        }
        (void)added_fiber;
    }
}

/* ── Spatial grid + alive list ───────────────────────────────────────────── */

void islands_build_grid(void)
{
    for (int ii = 0; ii < ISLAND_COUNT; ii++) {
        IslandDef *isl = &ISLAND_PRESETS[ii];

        /* Clear grid and alive list */
        memset(isl->wood_grid, 0, sizeof(isl->wood_grid));
        isl->alive_wood_count = 0;

        if (isl->resource_count == 0) continue;

        /* Compute bounding box of all wood nodes to set grid origin */
        float min_x =  1e9f, min_y =  1e9f;
        float max_x = -1e9f, max_y = -1e9f;
        for (int ri = 0; ri < isl->resource_count; ri++) {
            const IslandResource *r = &isl->resources[ri];
            if (r->type_id != RES_WOOD) continue;
            float wx = isl->x + r->ox;
            float wy = isl->y + r->oy;
            if (wx < min_x) min_x = wx;
            if (wy < min_y) min_y = wy;
            if (wx > max_x) max_x = wx;
            if (wy > max_y) max_y = wy;
        }
        if (min_x > max_x) continue; /* no wood nodes on this island */

        /* Grid origin: one cell-width before the first node so all nodes
         * map to col/row >= 0 even with floating-point rounding */
        isl->grid_ox = min_x - ISLAND_GRID_CELL_PX;
        isl->grid_oy = min_y - ISLAND_GRID_CELL_PX;
        isl->grid_w  = (int)((max_x - isl->grid_ox) / ISLAND_GRID_CELL_PX) + 2;
        isl->grid_h  = (int)((max_y - isl->grid_oy) / ISLAND_GRID_CELL_PX) + 2;
        if (isl->grid_w > ISLAND_GRID_COLS) isl->grid_w = ISLAND_GRID_COLS;
        if (isl->grid_h > ISLAND_GRID_ROWS) isl->grid_h = ISLAND_GRID_ROWS;

        /* Insert each wood node into the grid + alive list */
        for (int ri = 0; ri < isl->resource_count; ri++) {
            const IslandResource *r = &isl->resources[ri];
            if (r->type_id != RES_WOOD) continue;

            /* Add to alive list */
            if (isl->alive_wood_count < ISLAND_MAX_RESOURCES)
                isl->alive_wood[isl->alive_wood_count++] = (uint16_t)ri;

            /* Add to spatial grid */
            int col = (int)((isl->x + r->ox - isl->grid_ox) / ISLAND_GRID_CELL_PX);
            int row = (int)((isl->y + r->oy - isl->grid_oy) / ISLAND_GRID_CELL_PX);
            if (col < 0 || col >= isl->grid_w || row < 0 || row >= isl->grid_h) continue;
            IslandGridCell *cell = &isl->wood_grid[row][col];
            if (cell->count < ISLAND_GRID_MAXPC)
                cell->ri[cell->count++] = (uint16_t)ri;
        }
    }
}

void island_mark_tree_dead(IslandDef *isl, int ri)
{
    /* Remove from alive list (swap-and-pop) */
    for (int k = 0; k < isl->alive_wood_count; k++) {
        if (isl->alive_wood[k] == (uint16_t)ri) {
            isl->alive_wood[k] = isl->alive_wood[--isl->alive_wood_count];
            break;
        }
    }
    /* Remove from spatial grid (swap-and-pop in the cell) */
    int col = (int)((isl->x + isl->resources[ri].ox - isl->grid_ox) / ISLAND_GRID_CELL_PX);
    int row = (int)((isl->y + isl->resources[ri].oy - isl->grid_oy) / ISLAND_GRID_CELL_PX);
    if (col < 0 || col >= isl->grid_w || row < 0 || row >= isl->grid_h) return;
    IslandGridCell *cell = &isl->wood_grid[row][col];
    for (int k = 0; k < cell->count; k++) {
        if (cell->ri[k] == (uint16_t)ri) {
            cell->ri[k] = cell->ri[--cell->count];
            return;
        }
    }
}

/**
 * Returns true if the resource at world position (rx, ry) may respawn.
 * Suppressed when any active structure is within RESPAWN_SUPPRESS_R px,
 * i.e. a player has built over the depleted node's footprint.
 */
bool island_resource_can_respawn(float rx, float ry,
                                 const PlacedStructure *structs,
                                 uint32_t struct_count)
{
    /* Any structure type within this radius blocks respawn. */
    const float RESPAWN_SUPPRESS_R = 60.0f;
    for (uint32_t i = 0; i < struct_count; i++) {
        if (!structs[i].active) continue;
        float dx = structs[i].x - rx;
        float dy = structs[i].y - ry;
        if (dx*dx + dy*dy < RESPAWN_SUPPRESS_R * RESPAWN_SUPPRESS_R)
            return false;
    }
    return true;
}
